# Generated by Django 2.2.12 on 2020-04-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_order', '0002_order_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready_to_pick', 'Ready to Pick'), ('delivered', 'Deliverd'), ('processing', 'Processing')], default='pending', max_length=20),
        ),
    ]
