version: "3"

services:
  web:
    build:
      context: .
      args:
        SECRET_KEY: ${SECRET_KEY}
    env_file: .env
    volumes:
      - ./:/opt/webapp
    ports:
      - "8000:${PORT}"
  postgres:
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: chefout
    volumes:
      - ./postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"
