export const CATEGORY_REQUEST = "CATEGORY/CATEGORY_REQUEST";
export const CATEGORY_UPDATE = "CATEGORY/CATEGORY_UPDATE";

export const CATEGORY_ITEM_REQUEST = "CATEGORY/CATEGORY_ITEM_REQUEST";
export const CATEGORY_ITEM_UPDATE = "CATEGORY/CATEGORY_ITEM_UPDATE";

export const SET_SPECIFIC_ITEM = "CATEGORY/SET_SPECIFIC_ITEM";

export const CATEGORY_ITEM_NAVIGATE_REQUEST = "CATEGORY/CATEGORY_ITEM_NAVIGATE_REQUEST";
export const CATEGORY_ITEM_NAVIGATE = "CATEGORY/CATEGORY_ITEM_NAVIGATE";


export const UPDATE_CART = "CATEGORY/UPDATE_CART";
export const CLEAR_CART = "CATEGORY/CLEAR_CART";

export const REVIEW_ITEM_REQUEST = "ITEM/REVIEW_ITEM_REQUEST";
export const REVIEW_ITEM_COMPLETE = "ITEM/REVIEW_ITEM_COMPLETE";
export const REVIEW_ITEM_ERROR = "ITEM/REVIEW_ITEM_ERROR";