export const CONTACT_REQUEST = "CONTACT_REQUEST";
export const CONTACT_REQUEST_SUCCESS = "CONTACT_REQUEST_SUCCESS";
export const CONTACT_REQUEST_ERROR = "CONTACT_REQUEST_ERROR";

export const CONTACT_ADD = "CONTACT_ADD";
export const FINAL_ORDER_PLACE_REQUEST = "FINAL_ORDER_PLACE_REQUEST";
export const FINAL_ORDER_PLACE_ERROR = "FINAL_ORDER_PLACE_ERROR";
export const FINAL_ORDER_PLACE_SUCCESS = "FINAL_ORDER_PLACE_SUCCESS";