# Generated by Django 2.2.11 on 2020-03-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("prefix", models.CharField(max_length=8)),
                ("flag", models.URLField()),
            ],
        ),
    ]
