# Generated by Django 2.2.12 on 2020-04-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20200410_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariant',
            name='image',
            field=models.ImageField(upload_to='uploads/item_varient/'),
        ),
    ]
