# Generated by Django 2.2.13 on 2020-06-18 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200506_2321'),
        ('users', '0002_auto_20200325_1406'),
    ]

    operations = [
    ]
