# Generated by Django 2.2.12 on 2020-04-14 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("delivery_order", "0002_order_paymentmethod"),
        ("driver", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_created", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driverorder_driver",
                        to="driver.DriverProfile",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driverorder_order",
                        to="delivery_order.Order",
                    ),
                ),
            ],
        ),
    ]
