# Generated by Django 2.2.13 on 2020-06-19 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_order', '0002_auto_20200620_0045'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverorder',
            name='order',
        ),
        migrations.AddField(
            model_name='driverorder',
            name='bill',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='driverorder_bill', to='delivery_order.Bill'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='photo',
            field=models.ImageField(upload_to='uploads/driver/'),
        ),
    ]
