# Generated by Django 2.2.12 on 2020-04-14 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0002_driverorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverorder",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="driverorder_driver",
                to="driver.DriverOrder",
            ),
        ),
    ]
