# Generated by Django 2.2.12 on 2020-04-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_auto_20200414_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='photo',
            field=models.ImageField(upload_to='uploads/driver/'),
        ),
    ]
