# Generated by Django 2.2.12 on 2020-04-27 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_order', '0003_auto_20200428_0056'),
        ('driver', '0005_auto_20200422_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverorder',
            name='order',
        ),
        migrations.AddField(
            model_name='driverorder',
            name='bill',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='driverorder_bill', to='delivery_order.Bill'),
            preserve_default=False,
        ),
    ]
